name: Publish to PyPI
on:
  push:
    branches:
      - main
jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build wheel
        run: |
          python -m build --wheel

      - name: Save wheel
        uses: actions/upload-artifact@v2
        with:
          name: linux-wheel
          path: dist/*.whl
  
  publish:
    name: Publish to PyPI
    needs:
      - build-linux
    runs-on: ubuntu-latest

    steps:
      - name: Download all wheels
        uses: actions/download-artifact@v2
        with:
          path: wheels

      - name: Build dist directory
        run: |
          mkdir -p dist
          mv wheels/*/*.whl dist/
          rm -rf wheels
          ls dist/

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine

      - name: Publish to PyPI
        run: |
          twine upload dist/*.whl
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
